<?php
return array (
  'title' => '上传材料分类',
  'style' => '0',
  'siteid' => '0',
  'data' => 
  array (
    3383 => 
    array (
      'linkageid' => '3383',
      'name' => '1.申请家庭成员的身份证和户口簿',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3382',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '1',
    ),
    3384 => 
    array (
      'linkageid' => '3384',
      'name' => '2.已婚的提供结婚证',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3382',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '2',
    ),
    3385 => 
    array (
      'linkageid' => '3385',
      'name' => '3.丧偶的提供死亡证明',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3382',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '3',
    ),
    3386 => 
    array (
      'linkageid' => '3386',
      'name' => '4.离异的提供离婚证、离婚协议（或法院判决书）、离异后未婚',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3382',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '4',
    ),
    3387 => 
    array (
      'linkageid' => '3387',
      'name' => '5.申请家庭成员承租公房的提供公房租赁凭证',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3382',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '5',
    ),
    3388 => 
    array (
      'linkageid' => '3388',
      'name' => '6.申请家庭成员自有私房的提供房屋产权证，未办理产权证的提供正式房屋销售合同或其它房屋权属及面积的凭证',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3382',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
      'typecode' => '6',
    ),
    3389 => 
    array (
      'linkageid' => '3389',
      'name' => '7.申请家庭租住私房的提供房屋租赁合同',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3382',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '7',
    ),
    3390 => 
    array (
      'linkageid' => '3390',
      'name' => '8.有关单位在申请表内盖章确认的收入、住房证明',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3382',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '8',
    ),
    3391 => 
    array (
      'linkageid' => '3391',
      'name' => '9.申请家庭成员工作单位通过银行发放工资的储蓄存折（或银行对账单）或者单位的原始工资册（起止时间段为申请前12个月）',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3382',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
      'typecode' => '9',
    ),
    3392 => 
    array (
      'linkageid' => '3392',
      'name' => '10.家庭成员拥有的储蓄存款凭证',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3382',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '10',
    ),
    3393 => 
    array (
      'linkageid' => '3393',
      'name' => '11.家庭成员拥有的股票、基金、债券、商业保险凭证',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3382',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '11',
    ),
    3394 => 
    array (
      'linkageid' => '3394',
      'name' => '12.家庭成员拥有的车辆等凭证',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3382',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '12',
    ),
    3395 => 
    array (
      'linkageid' => '3395',
      'name' => '13.上一年度个人所得税完税证明或单位代扣代缴凭证',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3382',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '13',
    ),
    3396 => 
    array (
      'linkageid' => '3396',
      'name' => '14.无工作单位的，提供经过年审的失业证',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3382',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '14',
    ),
    3397 => 
    array (
      'linkageid' => '3397',
      'name' => '15.个体工商户提供经营执照、上年度个人所得税凭证',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3382',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '15',
    ),
    3398 => 
    array (
      'linkageid' => '3398',
      'name' => '16.已建立住房公积金账户的提交住房公积金缴存凭证',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3382',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '16',
    ),
    3399 => 
    array (
      'linkageid' => '3399',
      'name' => '17.城市低保、二级以上重度残疾、重点优抚对象、获得市级以上表彰等家庭，提供相关证件',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3382',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
      'typecode' => '17',
    ),
    3400 => 
    array (
      'linkageid' => '3400',
      'name' => '18.属于外来务工人员的提交社会保险缴交凭证、劳动合同',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3382',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '18',
    ),
    3401 => 
    array (
      'linkageid' => '3401',
      'name' => '19.属于普通全日制高校毕业生的提供毕业证书、社会保险缴交凭证、劳动合同',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3382',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
      'typecode' => '19',
    ),
    3402 => 
    array (
      'linkageid' => '3402',
      'name' => '20.属于机关事业单位已转正定级工作人员的申请人提交公务员主管部门出具的机关事业单位正式在编人员和转正定级的证明材料',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3382',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
      'typecode' => '20',
    ),
    3403 => 
    array (
      'linkageid' => '3403',
      'name' => '21.省直机关企事业单位工作人员还应提供工作单位开具的其未参加省直各类保障性住房申请的证明',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3382',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
      'typecode' => '21',
    ),
  ),
);
?>