<?php
return array (
  'title' => '关系',
  'style' => '0',
  'siteid' => '0',
  'data' => 
  array (
    3405 => 
    array (
      'linkageid' => '3405',
      'name' => '本人',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3404',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '-1',
    ),
    3407 => 
    array (
      'linkageid' => '3407',
      'name' => '其他',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3404',
      'listorder' => '1',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '0',
    ),
    3406 => 
    array (
      'linkageid' => '3406',
      'name' => '配偶',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3404',
      'listorder' => '2',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '1',
    ),
    3408 => 
    array (
      'linkageid' => '3408',
      'name' => '母亲',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3404',
      'listorder' => '3',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '2',
    ),
    3409 => 
    array (
      'linkageid' => '3409',
      'name' => '父亲',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3404',
      'listorder' => '4',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '3',
    ),
    3410 => 
    array (
      'linkageid' => '3410',
      'name' => '女儿',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3404',
      'listorder' => '5',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '4',
    ),
    3411 => 
    array (
      'linkageid' => '3411',
      'name' => '儿子',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3404',
      'listorder' => '6',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '5',
    ),
    3412 => 
    array (
      'linkageid' => '3412',
      'name' => '外婆',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3404',
      'listorder' => '7',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '6',
    ),
    3413 => 
    array (
      'linkageid' => '3413',
      'name' => '孙子',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3404',
      'listorder' => '8',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '8',
    ),
    3414 => 
    array (
      'linkageid' => '3414',
      'name' => '孙女',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3404',
      'listorder' => '9',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '9',
    ),
    3415 => 
    array (
      'linkageid' => '3415',
      'name' => '外公',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3404',
      'listorder' => '10',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '10',
    ),
    3416 => 
    array (
      'linkageid' => '3416',
      'name' => '奶奶',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3404',
      'listorder' => '11',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '11',
    ),
    3417 => 
    array (
      'linkageid' => '3417',
      'name' => '爷爷',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3404',
      'listorder' => '12',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '12',
    ),
    3418 => 
    array (
      'linkageid' => '3418',
      'name' => '外孙',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3404',
      'listorder' => '13',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '13',
    ),
    3419 => 
    array (
      'linkageid' => '3419',
      'name' => '外孙女',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3404',
      'listorder' => '14',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '14',
    ),
    3420 => 
    array (
      'linkageid' => '3420',
      'name' => '儿媳',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3404',
      'listorder' => '15',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '15',
    ),
    3421 => 
    array (
      'linkageid' => '3421',
      'name' => '女婿',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3404',
      'listorder' => '16',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '16',
    ),
    3422 => 
    array (
      'linkageid' => '3422',
      'name' => '孙媳',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3404',
      'listorder' => '17',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '17',
    ),
    3423 => 
    array (
      'linkageid' => '3423',
      'name' => '外孙媳',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3404',
      'listorder' => '18',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '18',
    ),
    3424 => 
    array (
      'linkageid' => '3424',
      'name' => '孙女婿',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3404',
      'listorder' => '19',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '19',
    ),
    3425 => 
    array (
      'linkageid' => '3425',
      'name' => '外孙女婿',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3404',
      'listorder' => '20',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '20',
    ),
  ),
);
?>