<?php
return array (
  'title' => '婚姻状况',
  'style' => '0',
  'siteid' => '0',
  'data' => 
  array (
    3427 => 
    array (
      'linkageid' => '3427',
      'name' => '未婚',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3426',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '0',
    ),
    3428 => 
    array (
      'linkageid' => '3428',
      'name' => '已婚',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3426',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '2',
    ),
    3429 => 
    array (
      'linkageid' => '3429',
      'name' => '丧偶',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3426',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '4',
    ),
    3430 => 
    array (
      'linkageid' => '3430',
      'name' => '离婚',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3426',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '3',
    ),
    3431 => 
    array (
      'linkageid' => '3431',
      'name' => '再婚',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3426',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '5',
    ),
  ),
);
?>