<?php
return array (
  'title' => '注册类型',
  'style' => '0',
  'siteid' => '0',
  'data' => 
  array (
    3433 => 
    array (
      'linkageid' => '3433',
      'name' => '国有企业',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3433',
      'keyid' => '3432',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
      'typecode' => NULL,
    ),
    3434 => 
    array (
      'linkageid' => '3434',
      'name' => '集体企业',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3434',
      'keyid' => '3432',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
      'typecode' => NULL,
    ),
    3435 => 
    array (
      'linkageid' => '3435',
      'name' => '股份合作企业',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3435',
      'keyid' => '3432',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
      'typecode' => NULL,
    ),
    3436 => 
    array (
      'linkageid' => '3436',
      'name' => '联营企业',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3436',
      'keyid' => '3432',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
      'typecode' => NULL,
    ),
    3437 => 
    array (
      'linkageid' => '3437',
      'name' => '有限责任公司',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3437',
      'keyid' => '3432',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
      'typecode' => NULL,
    ),
    3438 => 
    array (
      'linkageid' => '3438',
      'name' => '股份有限公司',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3438',
      'keyid' => '3432',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
      'typecode' => NULL,
    ),
    3439 => 
    array (
      'linkageid' => '3439',
      'name' => '私营企业',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3439',
      'keyid' => '3432',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
      'typecode' => NULL,
    ),
    3440 => 
    array (
      'linkageid' => '3440',
      'name' => '其他企业（内资）',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3440',
      'keyid' => '3432',
      'listorder' => '0',
      'description' => '',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
      'typecode' => NULL,
    ),
    3441 => 
    array (
      'linkageid' => '3441',
      'name' => '与港澳台商合资经营企业',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3441',
      'keyid' => '3432',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => NULL,
    ),
    3442 => 
    array (
      'linkageid' => '3442',
      'name' => '与港澳台商合作经营企业',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3442',
      'keyid' => '3432',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => NULL,
    ),
    3443 => 
    array (
      'linkageid' => '3443',
      'name' => '港澳台商独资经营企业',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3443',
      'keyid' => '3432',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => NULL,
    ),
    3444 => 
    array (
      'linkageid' => '3444',
      'name' => '港澳台商投资股份有限公司',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3444',
      'keyid' => '3432',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => NULL,
    ),
    3445 => 
    array (
      'linkageid' => '3445',
      'name' => '中外合资经营企业',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3445',
      'keyid' => '3432',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => NULL,
    ),
    3446 => 
    array (
      'linkageid' => '3446',
      'name' => '中外合作经营企业',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3446',
      'keyid' => '3432',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => NULL,
    ),
    3447 => 
    array (
      'linkageid' => '3447',
      'name' => '外资企业',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3447',
      'keyid' => '3432',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => NULL,
    ),
    3448 => 
    array (
      'linkageid' => '3448',
      'name' => '外商投资股份有限公司',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3448',
      'keyid' => '3432',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => NULL,
    ),
    3449 => 
    array (
      'linkageid' => '3449',
      'name' => '个体户',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3449',
      'keyid' => '3432',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => NULL,
    ),
    3450 => 
    array (
      'linkageid' => '3450',
      'name' => '个人合伙',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3450',
      'keyid' => '3432',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => NULL,
    ),
  ),
);
?>