<?php
return array (
  'title' => '住建厅-廉租房业务流程',
  'style' => '0',
  'siteid' => '0',
  'data' => 
  array (
    3462 => 
    array (
      'linkageid' => '3462',
      'name' => '提交住房保障申请',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '街道受理',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
      'typecode' => 'FJ00116001.1.1',
    ),
    3463 => 
    array (
      'linkageid' => '3463',
      'name' => '办事人员录入申请信息',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '街道受理',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
      'typecode' => 'FJ00116001.1.2',
    ),
    3464 => 
    array (
      'linkageid' => '3464',
      'name' => '住房保障申请受理',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '街道受理',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.1.3',
    ),
    3465 => 
    array (
      'linkageid' => '3465',
      'name' => '打印书面凭证',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '街道受理',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.1.4',
    ),
    3466 => 
    array (
      'linkageid' => '3466',
      'name' => '正式提交',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '街道受理',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.1.5',
    ),
    3467 => 
    array (
      'linkageid' => '3467',
      'name' => '审查申请要件内容',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '街道初审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.2.1',
    ),
    3468 => 
    array (
      'linkageid' => '3468',
      'name' => '街道公示',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '街道初审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.2.2',
    ),
    3469 => 
    array (
      'linkageid' => '3469',
      'name' => '街道办事人员调查（公示异议）',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '街道初审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.2.3',
    ),
    3470 => 
    array (
      'linkageid' => '3470',
      'name' => '街道办事人员出具初审意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '街道初审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.2.4',
    ),
    3471 => 
    array (
      'linkageid' => '3471',
      'name' => '街道办事人员出具不通过意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '街道初审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.2.5',
    ),
    3472 => 
    array (
      'linkageid' => '3472',
      'name' => '提交街道初审最终意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '街道初审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.2.6',
    ),
    3473 => 
    array (
      'linkageid' => '3473',
      'name' => '收到街道申请材料和初审意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.3.1',
    ),
    3474 => 
    array (
      'linkageid' => '3474',
      'name' => '房管总门核查住房情况',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.3.2',
    ),
    3475 => 
    array (
      'linkageid' => '3475',
      'name' => '公积金管理部门梳查公积金缴交情况',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.3.3',
    ),
    3476 => 
    array (
      'linkageid' => '3476',
      'name' => '经办人审查',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.3.4',
    ),
    3477 => 
    array (
      'linkageid' => '3477',
      'name' => '业务处室审核',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.3.5',
    ),
    3478 => 
    array (
      'linkageid' => '3478',
      'name' => '领导审批',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.3.6',
    ),
    3479 => 
    array (
      'linkageid' => '3479',
      'name' => '提交复审意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.3.7',
    ),
    3480 => 
    array (
      'linkageid' => '3480',
      'name' => '收到县（市、区）住建部门申请材料和复审意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '区民政部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.4.1',
    ),
    3481 => 
    array (
      'linkageid' => '3481',
      'name' => '提请相关部门联合核查',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '区民政部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.4.2',
    ),
    3482 => 
    array (
      'linkageid' => '3482',
      'name' => '多部门联合核查',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '区民政部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.4.3',
    ),
    3483 => 
    array (
      'linkageid' => '3483',
      'name' => '民政部门汇总',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '区民政部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.4.4',
    ),
    3484 => 
    array (
      'linkageid' => '3484',
      'name' => '提交汇总信息给住建部门',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '区民政部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.4.5',
    ),
    3485 => 
    array (
      'linkageid' => '3485',
      'name' => '收到区住建部门复审意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '区住建部门汇总',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.5.1',
    ),
    3486 => 
    array (
      'linkageid' => '3486',
      'name' => '收到区民政部门收入资产证明',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '区住建部门汇总',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.5.2',
    ),
    3487 => 
    array (
      'linkageid' => '3487',
      'name' => '汇总复审意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '区住建部门汇总',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.5.3',
    ),
    3488 => 
    array (
      'linkageid' => '3488',
      'name' => '提交汇总材料到设区市住建部门',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '区住建部门汇总',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.5.4',
    ),
    3489 => 
    array (
      'linkageid' => '3489',
      'name' => '收到区民政部门收入和资产证明',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '设区市住建部门复核认定',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.6.1',
    ),
    3490 => 
    array (
      'linkageid' => '3490',
      'name' => '多部门联合复核认定',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '设区市住建部门复核认定',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.6.2',
    ),
    3491 => 
    array (
      'linkageid' => '3491',
      'name' => '住建部门公示',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '设区市住建部门复核认定',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.6.3',
    ),
    3492 => 
    array (
      'linkageid' => '3492',
      'name' => '经办人员调查申请人相关情况',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '设区市住建部门复核认定',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.6.4',
    ),
    3493 => 
    array (
      'linkageid' => '3493',
      'name' => '进入轮候',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '设区市住建部门复核认定',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.6.5',
    ),
    3494 => 
    array (
      'linkageid' => '3494',
      'name' => '组织选房',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '设区市配租配售',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.7.1',
    ),
    3495 => 
    array (
      'linkageid' => '3495',
      'name' => '记录选房结果',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '设区市配租配售',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.7.2',
    ),
    3496 => 
    array (
      'linkageid' => '3496',
      'name' => '公布选房结果',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '设区市配租配售',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.7.3',
    ),
    3497 => 
    array (
      'linkageid' => '3497',
      'name' => '签订租售合同',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '设区市配租配售',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.7.4',
    ),
    3498 => 
    array (
      'linkageid' => '3498',
      'name' => '申请入住',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '设区市配租配售',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.7.5',
    ),
    3499 => 
    array (
      'linkageid' => '3499',
      'name' => '配置完成',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3461',
      'listorder' => '0',
      'description' => '设区市配租配售',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116001.7.6',
    ),
  ),
);
?>