<?php
return array (
  'title' => '住建厅-经济适用房业务流程',
  'style' => '0',
  'siteid' => '0',
  'data' => 
  array (
    3501 => 
    array (
      'linkageid' => '3501',
      'name' => '提交住房保障申请',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '街道受理',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.1.1',
    ),
    3502 => 
    array (
      'linkageid' => '3502',
      'name' => '办事人员录入申请信息',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '街道受理',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.1.2',
    ),
    3503 => 
    array (
      'linkageid' => '3503',
      'name' => '住房保障申请受理',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '街道受理',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.1.3',
    ),
    3504 => 
    array (
      'linkageid' => '3504',
      'name' => '打印书面凭证',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '街道受理',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.1.4',
    ),
    3505 => 
    array (
      'linkageid' => '3505',
      'name' => '正式提交',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '街道受理',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.1.5',
    ),
    3506 => 
    array (
      'linkageid' => '3506',
      'name' => '审查申请要件内容',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '街道初审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.2.1',
    ),
    3507 => 
    array (
      'linkageid' => '3507',
      'name' => '街道公示',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '街道初审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.2.2',
    ),
    3508 => 
    array (
      'linkageid' => '3508',
      'name' => '街道办事人员调查（公示异议）',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '街道初审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.2.3',
    ),
    3509 => 
    array (
      'linkageid' => '3509',
      'name' => '街道办事人员出具初审意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '街道初审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.2.4',
    ),
    3510 => 
    array (
      'linkageid' => '3510',
      'name' => '街道办事人员出具不通过意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '街道初审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.2.5',
    ),
    3511 => 
    array (
      'linkageid' => '3511',
      'name' => '提交街道初审最终意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '街道初审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.2.6',
    ),
    3512 => 
    array (
      'linkageid' => '3512',
      'name' => '收到街道申请材料和初审意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.3.1',
    ),
    3513 => 
    array (
      'linkageid' => '3513',
      'name' => '房管总门核查住房情况',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.3.2',
    ),
    3514 => 
    array (
      'linkageid' => '3514',
      'name' => '公积金管理部门梳查公积金缴交情况',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.3.3',
    ),
    3515 => 
    array (
      'linkageid' => '3515',
      'name' => '经办人审查',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.3.4',
    ),
    3516 => 
    array (
      'linkageid' => '3516',
      'name' => '业务处室审核',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.3.5',
    ),
    3517 => 
    array (
      'linkageid' => '3517',
      'name' => '领导审批',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.3.6',
    ),
    3518 => 
    array (
      'linkageid' => '3518',
      'name' => '提交复审意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.3.7',
    ),
    3519 => 
    array (
      'linkageid' => '3519',
      'name' => '收到县（市、区）住建部门申请材料和复审意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '区民政部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.4.1',
    ),
    3520 => 
    array (
      'linkageid' => '3520',
      'name' => '提请相关部门联合核查',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '区民政部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.4.2',
    ),
    3521 => 
    array (
      'linkageid' => '3521',
      'name' => '多部门联合核查',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '区民政部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.4.3',
    ),
    3522 => 
    array (
      'linkageid' => '3522',
      'name' => '民政部门汇总',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '区民政部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.4.4',
    ),
    3523 => 
    array (
      'linkageid' => '3523',
      'name' => '提交汇总信息给住建部门',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '区民政部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.4.5',
    ),
    3524 => 
    array (
      'linkageid' => '3524',
      'name' => '收到区住建部门复审意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '区住建部门汇总',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.5.1',
    ),
    3525 => 
    array (
      'linkageid' => '3525',
      'name' => '收到区民政部门收入资产证明',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '区住建部门汇总',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.5.2',
    ),
    3526 => 
    array (
      'linkageid' => '3526',
      'name' => '汇总复审意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '区住建部门汇总',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.5.3',
    ),
    3527 => 
    array (
      'linkageid' => '3527',
      'name' => '提交汇总材料到设区市住建部门',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '区住建部门汇总',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.5.4',
    ),
    3528 => 
    array (
      'linkageid' => '3528',
      'name' => '收到区民政部门收入和资产证明',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '设区市住建部门复核认定',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.6.1',
    ),
    3529 => 
    array (
      'linkageid' => '3529',
      'name' => '多部门联合复核认定',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '设区市住建部门复核认定',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.6.2',
    ),
    3530 => 
    array (
      'linkageid' => '3530',
      'name' => '住建部门公示',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '设区市住建部门复核认定',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.6.3',
    ),
    3531 => 
    array (
      'linkageid' => '3531',
      'name' => '经办人员调查申请人相关情况',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '设区市住建部门复核认定',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.6.4',
    ),
    3532 => 
    array (
      'linkageid' => '3532',
      'name' => '进入轮候',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '设区市住建部门复核认定',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.6.5',
    ),
    3533 => 
    array (
      'linkageid' => '3533',
      'name' => '组织选房',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '设区市配租配售',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.7.1',
    ),
    3534 => 
    array (
      'linkageid' => '3534',
      'name' => '记录选房结果',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '设区市配租配售',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.7.2',
    ),
    3535 => 
    array (
      'linkageid' => '3535',
      'name' => '公布选房结果',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '设区市配租配售',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.7.3',
    ),
    3536 => 
    array (
      'linkageid' => '3536',
      'name' => '签订租售合同',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '设区市配租配售',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.7.4',
    ),
    3537 => 
    array (
      'linkageid' => '3537',
      'name' => '申请入住',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '设区市配租配售',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.7.5',
    ),
    3538 => 
    array (
      'linkageid' => '3538',
      'name' => '配置完成',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3500',
      'listorder' => '0',
      'description' => '设区市配租配售',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116002.7.6',
    ),
  ),
);
?>