<?php
return array (
  'title' => '住建厅-公共租赁住房业务流程',
  'style' => '0',
  'siteid' => '0',
  'data' => 
  array (
    3540 => 
    array (
      'linkageid' => '3540',
      'name' => '提交住房保障申请',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '街道受理',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.1.1',
    ),
    3541 => 
    array (
      'linkageid' => '3541',
      'name' => '办事人员录入申请信息',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '街道受理',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.1.2',
    ),
    3542 => 
    array (
      'linkageid' => '3542',
      'name' => '住房保障申请受理',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '街道受理',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.1.3',
    ),
    3543 => 
    array (
      'linkageid' => '3543',
      'name' => '打印书面凭证',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '街道受理',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.1.4',
    ),
    3544 => 
    array (
      'linkageid' => '3544',
      'name' => '正式提交',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '街道受理',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.1.5',
    ),
    3545 => 
    array (
      'linkageid' => '3545',
      'name' => '审查申请要件内容',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '街道初审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.2.1',
    ),
    3546 => 
    array (
      'linkageid' => '3546',
      'name' => '街道公示',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '街道初审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.2.2',
    ),
    3547 => 
    array (
      'linkageid' => '3547',
      'name' => '街道办事人员调查（公示异议）',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '街道初审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.2.3',
    ),
    3548 => 
    array (
      'linkageid' => '3548',
      'name' => '街道办事人员出具初审意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '街道初审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.2.4',
    ),
    3549 => 
    array (
      'linkageid' => '3549',
      'name' => '街道办事人员出具不通过意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '街道初审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.2.5',
    ),
    3550 => 
    array (
      'linkageid' => '3550',
      'name' => '提交街道初审最终意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '街道初审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.2.6',
    ),
    3551 => 
    array (
      'linkageid' => '3551',
      'name' => '收到街道申请材料和初审意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.3.1',
    ),
    3552 => 
    array (
      'linkageid' => '3552',
      'name' => '房管总门核查住房情况',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.3.2',
    ),
    3553 => 
    array (
      'linkageid' => '3553',
      'name' => '公积金管理部门梳查公积金缴交情况',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.3.3',
    ),
    3554 => 
    array (
      'linkageid' => '3554',
      'name' => '经办人审查',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.3.4',
    ),
    3555 => 
    array (
      'linkageid' => '3555',
      'name' => '业务处室审核',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.3.5',
    ),
    3556 => 
    array (
      'linkageid' => '3556',
      'name' => '领导审批',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.3.6',
    ),
    3557 => 
    array (
      'linkageid' => '3557',
      'name' => '提交复审意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.3.7',
    ),
    3558 => 
    array (
      'linkageid' => '3558',
      'name' => '收到县（市、区）住建部门申请材料和复审意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '区民政部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.4.1',
    ),
    3559 => 
    array (
      'linkageid' => '3559',
      'name' => '提请相关部门联合核查',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '区民政部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.4.2',
    ),
    3560 => 
    array (
      'linkageid' => '3560',
      'name' => '多部门联合核查',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '区民政部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.4.3',
    ),
    3561 => 
    array (
      'linkageid' => '3561',
      'name' => '民政部门汇总',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '区民政部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.4.4',
    ),
    3562 => 
    array (
      'linkageid' => '3562',
      'name' => '提交汇总信息给住建部门',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '区民政部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.4.5',
    ),
    3563 => 
    array (
      'linkageid' => '3563',
      'name' => '收到区住建部门复审意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '区住建部门汇总',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.5.1',
    ),
    3564 => 
    array (
      'linkageid' => '3564',
      'name' => '收到区民政部门收入资产证明',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '区住建部门汇总',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.5.2',
    ),
    3565 => 
    array (
      'linkageid' => '3565',
      'name' => '汇总复审意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '区住建部门汇总',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.5.3',
    ),
    3566 => 
    array (
      'linkageid' => '3566',
      'name' => '提交汇总材料到设区市住建部门',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '区住建部门汇总',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.5.4',
    ),
    3567 => 
    array (
      'linkageid' => '3567',
      'name' => '收到区民政部门收入和资产证明',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '设区市住建部门复核认定',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.6.1',
    ),
    3568 => 
    array (
      'linkageid' => '3568',
      'name' => '多部门联合复核认定',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '设区市住建部门复核认定',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.6.2',
    ),
    3569 => 
    array (
      'linkageid' => '3569',
      'name' => '住建部门公示',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '设区市住建部门复核认定',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.6.3',
    ),
    3570 => 
    array (
      'linkageid' => '3570',
      'name' => '经办人员调查申请人相关情况',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '设区市住建部门复核认定',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.6.4',
    ),
    3571 => 
    array (
      'linkageid' => '3571',
      'name' => '进入轮候',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '设区市住建部门复核认定',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.6.5',
    ),
    3572 => 
    array (
      'linkageid' => '3572',
      'name' => '组织选房',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '设区市配租配售',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.7.1',
    ),
    3573 => 
    array (
      'linkageid' => '3573',
      'name' => '记录选房结果',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '设区市配租配售',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.7.2',
    ),
    3574 => 
    array (
      'linkageid' => '3574',
      'name' => '公布选房结果',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '设区市配租配售',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.7.3',
    ),
    3575 => 
    array (
      'linkageid' => '3575',
      'name' => '签订租售合同',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '设区市配租配售',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.7.4',
    ),
    3576 => 
    array (
      'linkageid' => '3576',
      'name' => '申请入住',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '设区市配租配售',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.7.5',
    ),
    3577 => 
    array (
      'linkageid' => '3577',
      'name' => '配置完成',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3539',
      'listorder' => '0',
      'description' => '设区市配租配售',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116003.7.6',
    ),
  ),
);
?>