<?php
return array (
  'title' => '住建厅-限价商品住房业务流程',
  'style' => '0',
  'siteid' => '0',
  'data' => 
  array (
    3579 => 
    array (
      'linkageid' => '3579',
      'name' => '提交住房保障申请',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '街道受理',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.1.1',
    ),
    3580 => 
    array (
      'linkageid' => '3580',
      'name' => '办事人员录入申请信息',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '街道受理',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.1.2',
    ),
    3581 => 
    array (
      'linkageid' => '3581',
      'name' => '住房保障申请受理',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '街道受理',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.1.3',
    ),
    3582 => 
    array (
      'linkageid' => '3582',
      'name' => '打印书面凭证',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '街道受理',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.1.4',
    ),
    3583 => 
    array (
      'linkageid' => '3583',
      'name' => '正式提交',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '街道受理',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.1.5',
    ),
    3584 => 
    array (
      'linkageid' => '3584',
      'name' => '审查申请要件内容',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '街道初审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.2.1',
    ),
    3585 => 
    array (
      'linkageid' => '3585',
      'name' => '街道公示',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '街道初审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.2.2',
    ),
    3586 => 
    array (
      'linkageid' => '3586',
      'name' => '街道办事人员调查（公示异议）',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '街道初审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.2.3',
    ),
    3587 => 
    array (
      'linkageid' => '3587',
      'name' => '街道办事人员出具初审意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '街道初审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.2.4',
    ),
    3588 => 
    array (
      'linkageid' => '3588',
      'name' => '街道办事人员出具不通过意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '街道初审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.2.5',
    ),
    3589 => 
    array (
      'linkageid' => '3589',
      'name' => '提交街道初审最终意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '街道初审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.2.6',
    ),
    3590 => 
    array (
      'linkageid' => '3590',
      'name' => '收到街道申请材料和初审意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.3.1',
    ),
    3591 => 
    array (
      'linkageid' => '3591',
      'name' => '房管总门核查住房情况',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.3.2',
    ),
    3592 => 
    array (
      'linkageid' => '3592',
      'name' => '公积金管理部门梳查公积金缴交情况',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.3.3',
    ),
    3593 => 
    array (
      'linkageid' => '3593',
      'name' => '经办人审查',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.3.4',
    ),
    3594 => 
    array (
      'linkageid' => '3594',
      'name' => '业务处室审核',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.3.5',
    ),
    3595 => 
    array (
      'linkageid' => '3595',
      'name' => '领导审批',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.3.6',
    ),
    3596 => 
    array (
      'linkageid' => '3596',
      'name' => '提交复审意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '区住建部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.3.7',
    ),
    3597 => 
    array (
      'linkageid' => '3597',
      'name' => '收到县（市、区）住建部门申请材料和复审意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '区民政部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.4.1',
    ),
    3598 => 
    array (
      'linkageid' => '3598',
      'name' => '提请相关部门联合核查',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '区民政部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.4.2',
    ),
    3599 => 
    array (
      'linkageid' => '3599',
      'name' => '多部门联合核查',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '区民政部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.4.3',
    ),
    3600 => 
    array (
      'linkageid' => '3600',
      'name' => '民政部门汇总',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '区民政部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.4.4',
    ),
    3601 => 
    array (
      'linkageid' => '3601',
      'name' => '提交汇总信息给住建部门',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '区民政部门复审',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.4.5',
    ),
    3602 => 
    array (
      'linkageid' => '3602',
      'name' => '收到区住建部门复审意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '区住建部门汇总',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.5.1',
    ),
    3603 => 
    array (
      'linkageid' => '3603',
      'name' => '收到区民政部门收入资产证明',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '区住建部门汇总',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.5.2',
    ),
    3604 => 
    array (
      'linkageid' => '3604',
      'name' => '汇总复审意见',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '区住建部门汇总',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.5.3',
    ),
    3605 => 
    array (
      'linkageid' => '3605',
      'name' => '提交汇总材料到设区市住建部门',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '区住建部门汇总',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.5.4',
    ),
    3606 => 
    array (
      'linkageid' => '3606',
      'name' => '收到区民政部门收入和资产证明',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '设区市住建部门复核认定',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.6.1',
    ),
    3607 => 
    array (
      'linkageid' => '3607',
      'name' => '多部门联合复核认定',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '设区市住建部门复核认定',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.6.2',
    ),
    3608 => 
    array (
      'linkageid' => '3608',
      'name' => '住建部门公示',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '设区市住建部门复核认定',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.6.3',
    ),
    3609 => 
    array (
      'linkageid' => '3609',
      'name' => '经办人员调查申请人相关情况',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '设区市住建部门复核认定',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.6.4',
    ),
    3610 => 
    array (
      'linkageid' => '3610',
      'name' => '进入轮候',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '设区市住建部门复核认定',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.6.5',
    ),
    3611 => 
    array (
      'linkageid' => '3611',
      'name' => '组织选房',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '设区市配租配售',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.7.1',
    ),
    3612 => 
    array (
      'linkageid' => '3612',
      'name' => '记录选房结果',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '设区市配租配售',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.7.2',
    ),
    3613 => 
    array (
      'linkageid' => '3613',
      'name' => '公布选房结果',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '设区市配租配售',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.7.3',
    ),
    3614 => 
    array (
      'linkageid' => '3614',
      'name' => '签订租售合同',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '设区市配租配售',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.7.4',
    ),
    3615 => 
    array (
      'linkageid' => '3615',
      'name' => '申请入住',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '设区市配租配售',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.7.5',
    ),
    3616 => 
    array (
      'linkageid' => '3616',
      'name' => '配置完成',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3578',
      'listorder' => '0',
      'description' => '设区市配租配售',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => 'FJ00116004.7.6',
    ),
  ),
);
?>