<?php
return array (
  'title' => '优先条件',
  'style' => '0',
  'siteid' => '0',
  'data' => 
  array (
    4435 => 
    array (
      'linkageid' => '4435',
      'name' => '低保家庭',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4434',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '',
    ),
    4436 => 
    array (
      'linkageid' => '4436',
      'name' => '民政优抚对象',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4434',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '',
    ),
    4437 => 
    array (
      'linkageid' => '4437',
      'name' => '年满60周岁老年人',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4434',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '',
    ),
    4438 => 
    array (
      'linkageid' => '4438',
      'name' => '二级以上残疾人',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4434',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '',
    ),
    4439 => 
    array (
      'linkageid' => '4439',
      'name' => '失独家庭',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4434',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '',
    ),
    4440 => 
    array (
      'linkageid' => '4440',
      'name' => '获得市级以上见义勇为表彰，特殊贡献奖励，劳动模范称号的人员',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4434',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '',
    ),
  ),
);
?>