<?php
return array (
  'title' => '省厅接口返回值',
  'style' => '0',
  'siteid' => '0',
  'data' => 
  array (
    4474 => 
    array (
      'linkageid' => '4474',
      'name' => '成功',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4473',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '000',
    ),
    4475 => 
    array (
      'linkageid' => '4475',
      'name' => '用户id或密码错误',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4473',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '001',
    ),
    4476 => 
    array (
      'linkageid' => '4476',
      'name' => '登陆key失效',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4473',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '002',
    ),
    4477 => 
    array (
      'linkageid' => '4477',
      'name' => '访问超时',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4473',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '003',
    ),
    4478 => 
    array (
      'linkageid' => '4478',
      'name' => '输入参数有误',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4473',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '004',
    ),
    4479 => 
    array (
      'linkageid' => '4479',
      'name' => '调用目标服务失败',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4473',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '005',
    ),
    4480 => 
    array (
      'linkageid' => '4480',
      'name' => 'IP校验失败',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4473',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '006',
    ),
    4481 => 
    array (
      'linkageid' => '4481',
      'name' => '非对接业务系统',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4473',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '007',
    ),
    4482 => 
    array (
      'linkageid' => '4482',
      'name' => '数据文件不完整',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4473',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '008',
    ),
    4483 => 
    array (
      'linkageid' => '4483',
      'name' => '数据格式不正确',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4473',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '009',
    ),
    4484 => 
    array (
      'linkageid' => '4484',
      'name' => '版本不相同',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4473',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '900',
    ),
    4485 => 
    array (
      'linkageid' => '4485',
      'name' => '其他错误',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4473',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '999',
    ),
    4486 => 
    array (
      'linkageid' => '4486',
      'name' => '文件不存在',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4473',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '800',
    ),
    4487 => 
    array (
      'linkageid' => '4487',
      'name' => '文件数量不正确',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4473',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '801',
    ),
    4488 => 
    array (
      'linkageid' => '4488',
      'name' => '路径不存在',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4473',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '802',
    ),
    4489 => 
    array (
      'linkageid' => '4489',
      'name' => '监察系统接收成功、业务系统推送成功',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4473',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '100',
    ),
    4490 => 
    array (
      'linkageid' => '4490',
      'name' => '监察系统接收成功、业务系统推送失败',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4473',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '101',
    ),
    4491 => 
    array (
      'linkageid' => '4491',
      'name' => '监察系统接收失败、业务系统推送成功',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4473',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '102',
    ),
    4492 => 
    array (
      'linkageid' => '4492',
      'name' => '监察系统接收失败、业务系统推送失败',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4473',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '103',
    ),
    4493 => 
    array (
      'linkageid' => '4493',
      'name' => '地市信息与推送平台不一致',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4473',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '201',
    ),
    4494 => 
    array (
      'linkageid' => '4494',
      'name' => '预警反馈信息未找到预警源数据',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4473',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '202',
    ),
    4495 => 
    array (
      'linkageid' => '4495',
      'name' => '扩展状态',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '4473',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
      'typecode' => '...',
    ),
  ),
);
?>